export const GROCERY_CATEGORIES = [
  "Produce",
  "Dairy",
  "Meat & Seafood",
  "Bakery",
  "Frozen",
  "Pantry",
  "Beverages",
  "Snacks",
  "Breakfast",
  "Household",
  "Personal Care",
  "Baby",
  "Pet",
  "Alcohol",
  "Deli",
  "Other",
] as const;

export type GroceryCategory = (typeof GROCERY_CATEGORIES)[number];

// Keyword mapping for auto-categorization
const CATEGORY_KEYWORDS: Record<GroceryCategory, string[]> = {
  Produce: [
    "apple",
    "banana",
    "tomato",
    "lettuce",
    "carrot",
    "onion",
    "potato",
    "pepper",
    "broccoli",
    "spinach",
    "fruit",
    "vegetable",
    "organic",
    "avocado",
    "berry",
    "strawberry",
    "blueberry",
    "grape",
    "orange",
    "lemon",
    "lime",
    "cucumber",
    "celery",
    "garlic",
    "mushroom",
    "squash",
    "zucchini",
    "corn",
    "peas",
    "beans",
    "cabbage",
    "kale",
    "arugula",
    "basil",
    "cilantro",
    "parsley",
    "melon",
    "watermelon",
    "cantaloupe",
    "pineapple",
    "mango",
    "peach",
    "pear",
    "plum",
    "cherry",
    "kiwi",
  ],
  Dairy: [
    "milk",
    "cheese",
    "yogurt",
    "butter",
    "cream",
    "sour cream",
    "cottage cheese",
    "half & half",
    "half and half",
    "dairy",
    "cheddar",
    "mozzarella",
    "parmesan",
    "feta",
    "brie",
    "goat cheese",
    "cream cheese",
    "whipped cream",
    "heavy cream",
    "light cream",
  ],
  "Meat & Seafood": [
    "chicken",
    "beef",
    "pork",
    "fish",
    "salmon",
    "shrimp",
    "turkey",
    "steak",
    "ground beef",
    "bacon",
    "sausage",
    "ham",
    "meat",
    "seafood",
    "tuna",
    "cod",
    "tilapia",
    "crab",
    "lobster",
    "scallop",
    "clam",
    "mussel",
    "lamb",
    "veal",
    "duck",
    "brisket",
    "ribs",
    "roast",
    "chop",
    "tenderloin",
    "sirloin",
  ],
  Bakery: [
    "bread",
    "bagel",
    "muffin",
    "donut",
    "croissant",
    "cake",
    "pastry",
    "roll",
    "baguette",
    "tortilla",
    "pita",
    "naan",
    "cookie",
    "brownie",
    "pie",
    "danish",
    "scone",
    "bun",
    "english muffin",
    "sourdough",
    "wheat bread",
    "white bread",
    "rye bread",
  ],
  Frozen: [
    "frozen",
    "ice cream",
    "pizza",
    "fries",
    "popsicle",
    "frozen meal",
    "frozen dinner",
    "frozen vegetable",
    "frozen fruit",
    "ice",
    "sorbet",
    "gelato",
    "frozen waffle",
    "frozen pancake",
    "frozen burrito",
    "frozen entree",
    "tv dinner",
  ],
  Pantry: [
    "rice",
    "pasta",
    "beans",
    "flour",
    "sugar",
    "oil",
    "sauce",
    "canned",
    "cereal",
    "soup",
    "spice",
    "condiment",
    "peanut butter",
    "jam",
    "jelly",
    "honey",
    "syrup",
    "vinegar",
    "salt",
    "pepper",
    "seasoning",
    "broth",
    "stock",
    "tomato sauce",
    "salsa",
    "ketchup",
    "mustard",
    "mayonnaise",
    "mayo",
    "relish",
    "pickle",
    "olive oil",
    "vegetable oil",
    "canola oil",
    "coconut oil",
    "baking soda",
    "baking powder",
    "yeast",
    "cornstarch",
    "vanilla",
    "extract",
  ],
  Beverages: [
    "soda",
    "juice",
    "water",
    "coffee",
    "tea",
    "energy drink",
    "sports drink",
    "beverage",
    "drink",
    "cola",
    "pepsi",
    "coke",
    "sprite",
    "lemonade",
    "gatorade",
    "red bull",
    "sparkling water",
    "seltzer",
    "kombucha",
    "smoothie",
    "milk shake",
  ],
  Snacks: [
    "chips",
    "crackers",
    "popcorn",
    "nuts",
    "candy",
    "chocolate",
    "cookies",
    "snack",
    "pretzels",
    "trail mix",
    "granola bar",
    "protein bar",
    "doritos",
    "lays",
    "cheetos",
    "oreo",
    "ritz",
    "goldfish",
    "pringles",
    "kitkat",
    "snickers",
    "reeses",
    "m&m",
    "skittles",
    "gummy",
  ],
  Breakfast: [
    "cereal",
    "oatmeal",
    "granola",
    "pancake",
    "waffle",
    "syrup",
    "breakfast bar",
    "pop tart",
    "cheerios",
    "frosted flakes",
    "corn flakes",
    "special k",
    "fruit loops",
    "lucky charms",
    "quaker",
    "instant oatmeal",
  ],
  Household: [
    "paper towel",
    "toilet paper",
    "trash bag",
    "cleaner",
    "detergent",
    "soap",
    "dish",
    "laundry",
    "napkin",
    "foil",
    "plastic wrap",
    "saran wrap",
    "ziploc",
    "garbage bag",
    "tissue",
    "kleenex",
    "bounty",
    "charmin",
    "lysol",
    "clorox",
    "windex",
    "tide",
    "dawn",
    "sponge",
    "scrubber",
    "mop",
    "broom",
    "duster",
    "air freshener",
    "febreze",
    "candle",
    "light bulb",
    "battery",
    "batteries",
  ],
  "Personal Care": [
    "shampoo",
    "conditioner",
    "toothpaste",
    "deodorant",
    "lotion",
    "razor",
    "soap",
    "cosmetic",
    "makeup",
    "skincare",
    "body wash",
    "hand soap",
    "face wash",
    "moisturizer",
    "sunscreen",
    "chapstick",
    "lip balm",
    "toothbrush",
    "floss",
    "mouthwash",
    "crest",
    "colgate",
    "dove",
    "olay",
    "neutrogena",
    "aveeno",
    "pantene",
    "head & shoulders",
    "gillette",
    "tampons",
    "pads",
    "feminine",
  ],
  Baby: [
    "diaper",
    "wipes",
    "formula",
    "baby food",
    "baby",
    "infant",
    "pampers",
    "huggies",
    "gerber",
    "baby wash",
    "baby lotion",
    "baby powder",
    "pacifier",
    "bottle",
  ],
  Pet: [
    "dog food",
    "cat food",
    "pet",
    "dog",
    "cat",
    "litter",
    "pet food",
    "dog treat",
    "cat treat",
    "pet treat",
    "purina",
    "pedigree",
    "friskies",
    "meow mix",
  ],
  Alcohol: [
    "wine",
    "beer",
    "vodka",
    "whiskey",
    "rum",
    "liquor",
    "alcohol",
    "champagne",
    "tequila",
    "gin",
    "brandy",
    "scotch",
    "bourbon",
    "ale",
    "lager",
    "ipa",
    "stout",
    "cider",
    "seltzer",
    "white claw",
    "truly",
    "bud light",
    "corona",
    "heineken",
  ],
  Deli: [
    "deli",
    "sliced",
    "sandwich meat",
    "rotisserie",
    "prepared meal",
    "salami",
    "bologna",
    "roast beef",
    "turkey breast",
    "ham",
    "pastrami",
    "prosciutto",
    "salad bar",
    "potato salad",
    "coleslaw",
    "hummus",
  ],
  Other: [],
};

/**
 * Categorizes an item based on its name using keyword matching
 * @param itemName The name of the item to categorize
 * @returns The grocery category that best matches the item
 */
export function categorizeItem(itemName: string): GroceryCategory {
  const normalized = itemName.toLowerCase().trim();

  // Check each category's keywords
  for (const [category, keywords] of Object.entries(CATEGORY_KEYWORDS)) {
    for (const keyword of keywords) {
      if (normalized.includes(keyword)) {
        return category as GroceryCategory;
      }
    }
  }

  return "Other";
}

/**
 * Categorizes multiple items in batch
 * @param items Array of items with rawName and id
 * @returns Record mapping item IDs to their categories
 */
export function categorizeBatch(
  items: { rawName: string; id: string }[]
): Record<string, GroceryCategory> {
  const result: Record<string, GroceryCategory> = {};
  for (const item of items) {
    result[item.id] = categorizeItem(item.rawName);
  }
  return result;
}
